runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /product/.*
  script: product.app

libraries:
- name: flask
  version: 0.12
- name: ssl
  version: latest
